name: Deploy Blog

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20.x' # or any other compatible version

      - name: Install Nuxt.js dependencies
        run: cd ./leona-blog && npm ci

      - name: Build Nuxt.js app
        run: cd ./leona-blog && npm run build

      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh/
          echo "${{ secrets.SSH_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts

      - name: Copy build to server
        run: |
          rsync -vrm ./leona-blog/.output/* ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}:/leona-blog

          ssh ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} 'cd /leona-blog && pm2 stop leona-blog || true && pm2 delete leona-blog || true'
          ssh ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} 'cd /leona-blog && pm2 restart index.mjs --name leona-blog'
