name: Deploy Blog

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Nuxt.js dependencies
        run: cd ./leona-blog && npm ci

      - name: Build Nuxt.js app
        run: cd ./leona-blog && npm run build

      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh/
          echo "${{ secrets.SSH_KEY }}" > ~/.ssh/id_rsa
          echo "${{ secrets.SSH_PUB_KEY }}" > ~/.ssh/id_rsa.pub
          chmod 600 ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa.pub
          ssh-keyscan -H ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts

      - name: Copy build to server
        run: |
          rsync -vrm ./leona-blog/dist/* ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}:~/leona-blog

      - name: Restart NodeJS
        run: |
          ssh ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} 'cd ~/leona-blog/server && pm2 restart leona-blog'
