name: Deploy Blog

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20.x' # or any other compatible version

      - name: Install Nuxt.js dependencies
        run: cd ./leona-blog && npm ci

      - name: Build Nuxt.js app
        run: npm run build

      - name: Deploy to VM
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            # Copy the built Nuxt.js app to the VM
            scp -r ./leona-blog/.output ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}:/leona-blog

            # Install Nuxt.js app dependencies on the VM (if applicable)
            # If your app doesn't require any additional dependencies, you can skip this step
            ssh ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} 'cd /leona-blog && npm install'

            # Restart the Nuxt.js app on the VM using pm2 (or any other process manager you use)
            # Replace 'APP_NAME' and 'APP_ENTRY_FILE' with the appropriate values for your app
            ssh ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} 'cd /leona-blog && pm2 stop leona-blog || true && pm2 delete leona-blog || true'
            ssh ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} 'cd /leona-blog && pm2 start index.mjs --name leona-blog'
